from typing import Protocol

from coach.schema import CanonicalSample, SessionContext


class TelemetrySource(Protocol):
    def open(self) -> None: ...
    def context(self) -> SessionContext: ...
    def read(self) -> CanonicalSample | None: ...
    def close(self) -> None: ...
